rem Update messages generated by buttons on Canvas panel using fart-it (https://github.com/lionello/fart-it)
fart -r -c -- public/build/canvas* "An error has occurred. Check console output for more details." "An error has occurred."
fart -r -c -- public/build/canvas* "API call was successful" "Command was successful"
